"use strict";
window.TP_LEGAL = {
privacy:{updated:"2025-07-01",title:{ar:"سياسة الخصوصية",en:"Privacy Policy"},sections:[
  {h:{ar:"المبدأ الأساسي",en:"Core principle"},p:{ar:["هذه المنصة موقع ثابت: كل أداة تعمل داخل متصفحك. النصوص التي تكتبها والصور التي تعالجها لا تُرسل إلى أي خادم ولا تُخزَّن بعد إغلاق الصفحة.","لا نجمع بيانات شخصية ولا نطلب تسجيلًا ولا نبيع بيانات لأي طرف."],en:["This platform is a static site: every tool runs inside your browser. The text you type and images you process are never sent to any server, nor stored after you close the page.","We collect no personal data, require no sign-up, and sell nothing to anyone."]}},
  {h:{ar:"ما يُخزَّن محليًا (localStorage)",en:"What is stored locally (localStorage)"},p:{ar:["ثلاث قيم فقط على جهازك: تفضيل الثيم (ليلي/نهاري)، أدواتك المفضلة، وآخر خمس أدوات استخدمتها. لا شيء منها يغادر جهازك، ويمكنك مسحه من إعدادات المتصفح متى شئت."],en:["Only three values, on your device: theme preference (dark/light), your favorite tools, and the last five tools you used. None leaves your device; clear them anytime from browser settings."]}},
  {h:{ar:"ملفاتك في أدوات الصور",en:"Your files in image tools"},p:{ar:["أدوات الصور تقرأ الملف من جهازك وتعالجه بـ Canvas داخل المتصفح، ثم تُنزَّل النتيجة مباشرة إلى جهازك. لا نحتفظ بنسخة، ولا نعرف اسم ملفك أصلًا. حد الحجم المقبول معلن في كل أداة، والملفات غير المدعومة تُرفض قبل أي معالجة."],en:["Image tools read the file from your device and process it via Canvas in the browser, then download the result straight back. We keep no copy and never even learn your file's name. A size limit is stated per tool; unsupported files are rejected before processing."]}},
  {h:{ar:"التحليلات والإعلانات",en:"Analytics and ads"},p:{ar:["حتى تاريخ آخر تحديث: لا تحليلات مفعّلة ولا إعلانات معروضة. عند تفعيل Google Analytics أو AdSense مستقبلًا، سيُحدَّث هذا القسم قبل التفعيل بما يشمله ذلك من ملفات تعريف طرف ثالث."],en:["As of the last update: no analytics enabled and no ads shown. If Google Analytics or AdSense is enabled in the future, this section will be updated before activation, covering any third-party cookies involved."]}},
  {h:{ar:"الخدمات الخارجية",en:"Third-party services"},p:{ar:["الخطوط تُحمَّل من Google Fonts بسياسة خصوصيتها الخاصة. روابط التواصل تقود لمنصات خارجية تُدار بسياساتها."],en:["Fonts load from Google Fonts under their own policy. Contact links lead to external platforms governed by their policies."]}}]},
terms:{updated:"2025-07-01",title:{ar:"شروط الاستخدام",en:"Terms of Use"},sections:[
  {h:{ar:"استخدام الأدوات",en:"Using the tools"},p:{ar:["الأدوات مجانية للاستخدام الشخصي والتجاري. يُمنع استخدام المنصة لإنتاج محتوى غير قانوني أو ضار."],en:["Tools are free for personal and commercial use. Using the platform to produce unlawful or harmful content is prohibited."]}},
  {h:{ar:"لا ضمان",en:"No warranty"},p:{ar:["الأدوات تُقدَّم \"كما هي\". تحقق دائمًا من المخرجات قبل الاعتماد عليها في عمل حرج — خاصة الأكواد المولّدة: راجعها قبل النشر."],en:["Tools are provided \"as is\". Always verify outputs before relying on them for critical work — especially generated code: review before publishing."]}},
  {h:{ar:"حدود المسؤولية",en:"Limitation of liability"},p:{ar:["لا يتحمل عبدالله عباس مسؤولية أي خسارة تنتج عن استخدام الأدوات أو الاعتماد على مخرجاتها."],en:["Abdallah Abas is not liable for any loss resulting from use of the tools or reliance on their outputs."]}}]},
disclaimer:{updated:"2025-07-01",title:{ar:"إخلاء المسؤولية",en:"Disclaimer"},sections:[
  {h:{ar:"طبيعة التحليل",en:"Nature of the analysis"},p:{ar:["أي مؤشرات طول أو بنية تظهر في الأدوات (كعدّادات العنوان والوصف) هي فحوص محلية مباشرة على مدخلاتك — وليست فحصًا لموقعك لدى Google ولا بديلًا عن أدواتها الرسمية. لا تدّعي المنصة ضمان ترتيب أو قبول AdSense أو أي نتيجة لدى أي جهة."],en:["Any length or structure indicators shown in tools (like title/description meters) are direct local checks on your input — not a check of your site with Google, nor a substitute for its official tools. The platform claims no guarantee of rankings, AdSense approval, or any outcome."]}},
  {h:{ar:"الأكواد المولّدة",en:"Generated code"},p:{ar:["مخرجات المولدات وسوم وأكواد قياسية نظيفة، لكن موقع كل مستخدم مختلف — راجع وكيّف قبل الاعتماد."],en:["Generator outputs are clean standard tags and code, but every site differs — review and adapt before relying on them."]}}]}
};
