/* Tool Registry — المصدر الوحيد لتعريف الأدوات.
   إضافة أداة = عنصر هنا + mount/content في js/tools.js (انظر README). */
"use strict";
window.TOOLS_REGISTRY = [
  { slug:"word-counter", cat:"content", icon:"type", popular:true, featured:true, added:"2025-07-01",
    name:{ar:"عداد الكلمات والحروف",en:"Word & Character Counter"},
    desc:{ar:"إحصاء فوري للكلمات والحروف والجمل والفقرات ووقت القراءة — أثناء الكتابة مباشرة.",
          en:"Instant word, character, sentence, paragraph and reading-time stats — as you type."},
    kw:{ar:["عدد الكلمات","عداد حروف","وقت القراءة"],en:["word count","character counter","reading time"]} },
  { slug:"text-cleaner", cat:"content", icon:"broom", popular:false, featured:false, added:"2025-07-01",
    name:{ar:"منظّف النص",en:"Text Cleaner"},
    desc:{ar:"إزالة المسافات الزائدة والأسطر الفارغة والتشكيل والتكرار — بخيارات تتحكم بها.",
          en:"Remove extra spaces, empty lines, diacritics and duplicates — with options you control."},
    kw:{ar:["تنظيف نص","مسافات زائدة","إزالة تشكيل"],en:["clean text","extra spaces","remove diacritics"]} },
  { slug:"slug-generator", cat:"seo", icon:"link", popular:false, featured:false, added:"2025-07-01",
    name:{ar:"مولّد Slug",en:"Slug Generator"},
    desc:{ar:"تحويل أي عنوان عربي أو إنجليزي إلى رابط URL نظيف — مع إزالة التشكيل والتطويل.",
          en:"Turn any Arabic or English title into a clean URL slug — diacritics and tatweel removed."},
    kw:{ar:["slug","رابط صديق للسيو","روابط عربية"],en:["slug","seo url","permalink"]} },
  { slug:"meta-tags-generator", cat:"blogger", icon:"code", popular:true, featured:true, added:"2025-07-01",
    name:{ar:"مولّد Meta Tags",en:"Meta Tags Generator"},
    desc:{ar:"توليد وسوم Meta وOpen Graph وTwitter كاملة جاهزة للصق — مع عدّاد طول للعنوان والوصف.",
          en:"Generate complete Meta, Open Graph and Twitter tags ready to paste — with title & description length meters."},
    kw:{ar:["meta tags","open graph","وسوم وصفية"],en:["meta tags","open graph","twitter card"]} },
  { slug:"robots-generator", cat:"blogger", icon:"shield", popular:false, featured:false, added:"2025-07-01",
    name:{ar:"مولّد Robots.txt",en:"Robots.txt Generator"},
    desc:{ar:"توليد ملف robots.txt صحيح بسيارات منع ومسار خريطة الموقع — مخرجات نظيفة جاهزة للرفع.",
          en:"Generate a correct robots.txt with disallow rules and sitemap path — clean, ready-to-upload output."},
    kw:{ar:["robots.txt","خريطة الموقع","منع الفهرسة"],en:["robots.txt","sitemap","disallow"]} },
  { slug:"json-formatter", cat:"dev", icon:"braces", popular:true, featured:false, added:"2025-07-01",
    name:{ar:"منسّق JSON",en:"JSON Formatter"},
    desc:{ar:"تنسيق أو تصغير JSON مع تحقق فوري — ورسالة خطأ تُبيّن موضع المشكلة سطرًا وعمودًا.",
          en:"Pretty-print or minify JSON with instant validation — errors reported with line and column."},
    kw:{ar:["json","تنسيق json","تحقق json"],en:["json","format json","validate json"]} },
  { slug:"base64", cat:"dev", icon:"binary", popular:false, featured:false, added:"2025-07-01",
    name:{ar:"Base64 ترميز وفك",en:"Base64 Encode / Decode"},
    desc:{ar:"ترميز وفك Base64 بدعم كامل للعربية (UTF-8) — في الاتجاهين دون أخطاء الترميز الشائعة.",
          en:"Base64 encode and decode with full UTF-8/Arabic support — both directions, no encoding bugs."},
    kw:{ar:["base64","ترميز","فك ترميز"],en:["base64","encode","decode"]} },
  { slug:"url-encoder", cat:"dev", icon:"globe", popular:false, featured:false, added:"2025-07-01",
    name:{ar:"ترميز وفك الروابط",en:"URL Encode / Decode"},
    desc:{ar:"ترميز وفك روابط ونصوص بعلامات خاصة — للمكونات الفردية بدقة encodeURIComponent.",
          en:"Encode and decode URLs and special characters — per-component, via encodeURIComponent."},
    kw:{ar:["url encode","ترميز روابط"],en:["url encode","percent encoding"]} },
  { slug:"color-converter", cat:"dev", icon:"palette", popular:false, featured:false, added:"2025-07-01",
    name:{ar:"محوّل الألوان",en:"Color Converter"},
    desc:{ar:"تحويل HEX إلى RGB وHSL مع معاينة حية للمرة — وأخذ اللون من منتقي النظام.",
          en:"Convert HEX to RGB and HSL with a live swatch — pick colors from the system picker too."},
    kw:{ar:["hex to rgb","ألوان","hsl"],en:["hex to rgb","color converter","hsl"]} },
  { slug:"timestamp-converter", cat:"dev", icon:"clock", popular:false, featured:false, added:"2025-07-01",
    name:{ar:"محوّل Timestamp",en:"Timestamp Converter"},
    desc:{ar:"تحويل UNIX Timestamp إلى تاريخ مقروء (محلي وUTC) والعكس — مع كشف تلقائي للثواني والملي ثانية.",
          en:"Convert UNIX timestamps to readable dates (local & UTC) and back — auto-detects seconds vs milliseconds."},
    kw:{ar:["timestamp","unix","تحويل وقت"],en:["timestamp","unix time","epoch"]} },
  { slug:"image-dimensions", cat:"images", icon:"image", popular:false, featured:false, added:"2025-07-01",
    name:{ar:"أبعاد الصورة",en:"Image Dimensions"},
    desc:{ar:"اعرض أبعاد الصورة ونوعها وحجمها فورًا — المعالجة داخل متصفحك والملف لا يُرفع لأي مكان.",
          en:"Instantly see an image's dimensions, type and file size — processed in your browser, never uploaded."},
    kw:{ar:["أبعاد الصورة","حجم الصورة","عرض وارتفاع"],en:["image dimensions","file size","width height"]} },
  { slug:"image-converter", cat:"images", icon:"swap", popular:true, featured:true, added:"2025-07-01",
    name:{ar:"تحويل وضغط الصور",en:"Image Converter & Compressor"},
    desc:{ar:"تحويل بين WebP وJPEG وPNG مع تحكم بجودة الضغط وتصغير الأبعاد اختياريًا — كل المعالجة محلية.",
          en:"Convert between WebP, JPEG and PNG with quality control and optional resizing — 100% local processing."},
    kw:{ar:["تحويل صور","webp","ضغط صور"],en:["image converter","webp","compress image"]} },
  { slug:"price-calculator", cat:"freelancer", icon:"briefcase", popular:false, featured:false, added:"2025-07-01",
    name:{ar:"حاسبة سعر الخدمة",en:"Service Price Calculator"},
    desc:{ar:"احسب سعر خدمتك من سعر الساعة وعدد الساعات والمصاريف وهامش الربح — بتفصيل واضح.",
          en:"Price your service from hourly rate, hours, expenses and profit margin — with a clear breakdown."},
    kw:{ar:["تسعير الخدمات","سعر الساعة","حاسبة فريلانس"],en:["freelance pricing","hourly rate","project price"]} }
];
